export type CountryPhoneCode = {
    code: string;
    country: string;
    emoji: string;
}

export const countryPhoneCodes: CountryPhoneCode[] = [
    { code: "+1", country: "United States", emoji: "🇺🇸" },
    { code: "+44", country: "United Kingdom", emoji: "🇬🇧" },
    { code: "+91", country: "India", emoji: "🇮🇳" },
    { code: "+61", country: "Australia", emoji: "🇦🇺" },
    { code: "+81", country: "Japan", emoji: "🇯🇵" },
    { code: "+49", country: "Germany", emoji: "🇩🇪" },
    { code: "+33", country: "France", emoji: "🇫🇷" },
    { code: "+39", country: "Italy", emoji: "🇮🇹" },
    { code: "+34", country: "Spain", emoji: "🇪🇸" },
    { code: "+86", country: "China", emoji: "🇨🇳" },
    { code: "+7", country: "Russia", emoji: "🇷🇺" },
    { code: "+55", country: "Brazil", emoji: "🇧🇷" },
    { code: "+27", country: "South Africa", emoji: "🇿🇦" },
    { code: "+82", country: "South Korea", emoji: "🇰🇷" },
    { code: "+880", country: "Bangladesh", emoji: "🇧🇩" },
    { code: "+92", country: "Pakistan", emoji: "🇵🇰" },
    { code: "+966", country: "Saudi Arabia", emoji: "🇸🇦" },
    { code: "+971", country: "United Arab Emirates", emoji: "🇦🇪" },
    { code: "+20", country: "Egypt", emoji: "🇪🇬" },
    { code: "+98", country: "Iran", emoji: "🇮🇷" },
    { code: "+62", country: "Indonesia", emoji: "🇮🇩" },
    { code: "+63", country: "Philippines", emoji: "🇵🇭" },
    { code: "+60", country: "Malaysia", emoji: "🇲🇾" },
    { code: "+65", country: "Singapore", emoji: "🇸🇬" },
    { code: "+66", country: "Thailand", emoji: "🇹🇭" },
    { code: "+84", country: "Vietnam", emoji: "🇻🇳" },
    { code: "+90", country: "Turkey", emoji: "🇹🇷" },
    { code: "+212", country: "Morocco", emoji: "🇲🇦" },
    { code: "+964", country: "Iraq", emoji: "🇮🇶" },
    { code: "+94", country: "Sri Lanka", emoji: "🇱🇰" },
    { code: "+254", country: "Kenya", emoji: "🇰🇪" },
    { code: "+256", country: "Uganda", emoji: "🇺🇬" },
    { code: "+234", country: "Nigeria", emoji: "🇳🇬" },
    { code: "+213", country: "Algeria", emoji: "🇩🇿" },
    { code: "+216", country: "Tunisia", emoji: "🇹🇳" },
    { code: "+962", country: "Jordan", emoji: "🇯🇴" },
    { code: "+974", country: "Qatar", emoji: "🇶🇦" },
    { code: "+968", country: "Oman", emoji: "🇴🇲" },
    { code: "+973", country: "Bahrain", emoji: "🇧🇭" },
    { code: "+965", country: "Kuwait", emoji: "🇰🇼" },
    { code: "+856", country: "Laos", emoji: "🇱🇦" },
    { code: "+855", country: "Cambodia", emoji: "🇰🇭" },
    { code: "+998", country: "Uzbekistan", emoji: "🇺🇿" },
    { code: "+380", country: "Ukraine", emoji: "🇺🇦" },
    { code: "+994", country: "Azerbaijan", emoji: "🇦🇿" },
    { code: "+995", country: "Georgia", emoji: "🇬🇪" },
    { code: "+961", country: "Lebanon", emoji: "🇱🇧" },
    { code: "+961", country: "Lebanon", emoji: "🇱🇧" },
    { code: "+1", country: "Canada", emoji: "🇨🇦" },
    { code: "+353", country: "Ireland", emoji: "🇮🇪" },
    { code: "+358", country: "Finland", emoji: "🇫🇮" },
    { code: "+46", country: "Sweden", emoji: "🇸🇪" },
    { code: "+47", country: "Norway", emoji: "🇳🇴" },
    { code: "+45", country: "Denmark", emoji: "🇩🇰" },
    { code: "+43", country: "Austria", emoji: "🇦🇹" },
    { code: "+41", country: "Switzerland", emoji: "🇨🇭" },
    { code: "+48", country: "Poland", emoji: "🇵🇱" },
    { code: "+420", country: "Czech Republic", emoji: "🇨🇿" },
    { code: "+421", country: "Slovakia", emoji: "🇸🇰" },
    { code: "+36", country: "Hungary", emoji: "🇭🇺" },
    { code: "+40", country: "Romania", emoji: "🇷🇴" },
    { code: "+30", country: "Greece", emoji: "🇬🇷" },
    { code: "+351", country: "Portugal", emoji: "🇵🇹" },
    { code: "+380", country: "Ukraine", emoji: "🇺🇦" },
    { code: "+48", country: "Poland", emoji: "🇵🇱" },
    { code: "+386", country: "Slovenia", emoji: "🇸🇮" },
    { code: "+385", country: "Croatia", emoji: "🇭🇷" },
    { code: "+381", country: "Serbia", emoji: "🇷🇸" },
    { code: "+382", country: "Montenegro", emoji: "🇲🇪" },
    { code: "+389", country: "North Macedonia", emoji: "🇲🇰" },
    { code: "+372", country: "Estonia", emoji: "🇪🇪" },
    { code: "+371", country: "Latvia", emoji: "🇱🇻" },
    { code: "+370", country: "Lithuania", emoji: "🇱🇹" },
    { code: "+994", country: "Azerbaijan", emoji: "🇦🇿" },
    { code: "+995", country: "Georgia", emoji: "🇬🇪" },
    { code: "+373", country: "Moldova", emoji: "🇲🇩" },
    { code: "+375", country: "Belarus", emoji: "🇧🇾" },
    { code: "+7", country: "Kazakhstan", emoji: "🇰🇿" },
    { code: "+998", country: "Uzbekistan", emoji: "🇺🇿" },
    { code: "+996", country: "Kyrgyzstan", emoji: "🇰🇬" },
    { code: "+992", country: "Tajikistan", emoji: "🇹🇯" },
    { code: "+993", country: "Turkmenistan", emoji: "🇹🇲" },
    { code: "+976", country: "Mongolia", emoji: "🇲🇳" },
    { code: "+95", country: "Myanmar", emoji: "🇲🇲" },
    { code: "+880", country: "Bangladesh", emoji: "🇧🇩" },
    { code: "+977", country: "Nepal", emoji: "🇳🇵" },
    { code: "+960", country: "Maldives", emoji: "🇲🇻" },
    { code: "+856", country: "Laos", emoji: "🇱🇦" },
    { code: "+855", country: "Cambodia", emoji: "🇰🇭" },
    { code: "+65", country: "Singapore", emoji: "🇸🇬" },
    { code: "+60", country: "Malaysia", emoji: "🇲🇾" },
    { code: "+66", country: "Thailand", emoji: "🇹🇭" },
    { code: "+84", country: "Vietnam", emoji: "🇻🇳" },
    { code: "+62", country: "Indonesia", emoji: "🇮🇩" },
    { code: "+63", country: "Philippines", emoji: "🇵🇭" },
    { code: "+64", country: "New Zealand", emoji: "🇳🇿" },
    { code: "+675", country: "Papua New Guinea", emoji: "🇵🇬" },
    { code: "+682", country: "Cook Islands", emoji: "🇨🇰" },
    { code: "+685", country: "Samoa", emoji: "🇼🇸" },
    { code: "+679", country: "Fiji", emoji: "🇫🇯" },
    { code: "+682", country: "Cook Islands", emoji: "🇨🇰" },
    { code: "+686", country: "Kiribati", emoji: "🇰🇮" },
    { code: "+691", country: "Micronesia", emoji: "🇫🇲" },
    { code: "+692", country: "Marshall Islands", emoji: "🇲🇭" },
    { code: "+850", country: "North Korea", emoji: "🇰🇵" },
    { code: "+82", country: "South Korea", emoji: "🇰🇷" },
    { code: "+81", country: "Japan", emoji: "🇯🇵" },
    { code: "+86", country: "China", emoji: "🇨🇳" },
    { code: "+852", country: "Hong Kong", emoji: "🇭🇰" },
    { code: "+853", country: "Macau", emoji: "🇲🇴" },
    { code: "+886", country: "Taiwan", emoji: "🇹🇼" },
    { code: "+92", country: "Pakistan", emoji: "🇵🇰" },
    { code: "+20", country: "Egypt", emoji: "🇪🇬" },
    { code: "+212", country: "Morocco", emoji: "🇲🇦" },
    { code: "+213", country: "Algeria", emoji: "🇩🇿" },
    { code: "+216", country: "Tunisia", emoji: "🇹🇳" },
    { code: "+218", country: "Libya", emoji: "🇱🇾" },
    { code: "+249", country: "Sudan", emoji: "🇸🇩" },
    { code: "+251", country: "Ethiopia", emoji: "🇪🇹" },
    { code: "+254", country: "Kenya", emoji: "🇰🇪" },
    { code: "+255", country: "Tanzania", emoji: "🇹🇿" },
    { code: "+256", country: "Uganda", emoji: "🇺🇬" },
    { code: "+260", country: "Zambia", emoji: "🇿🇲" },
    { code: "+263", country: "Zimbabwe", emoji: "🇿🇼" },
    { code: "+27", country: "South Africa", emoji: "🇿🇦" },
    { code: "+234", country: "Nigeria", emoji: "🇳🇬" },
    { code: "+233", country: "Ghana", emoji: "🇬🇭" },
    { code: "+225", country: "Ivory Coast", emoji: "🇨🇮" },
    { code: "+221", country: "Senegal", emoji: "🇸🇳" },
    { code: "+220", country: "Gambia", emoji: "🇬🇲" },
    { code: "+216", country: "Tunisia", emoji: "🇹🇳" },
    { code: "+218", country: "Libya", emoji: "🇱🇾" },
    { code: "+965", country: "Kuwait", emoji: "🇰🇼" },
    { code: "+974", country: "Qatar", emoji: "🇶🇦" },
    { code: "+968", country: "Oman", emoji: "🇴🇲" },
    { code: "+973", country: "Bahrain", emoji: "🇧🇭" },
    { code: "+972", country: "Israel", emoji: "🇮🇱" },
    { code: "+961", country: "Lebanon", emoji: "🇱🇧" },
    { code: "+963", country: "Syria", emoji: "🇸🇾" },
    { code: "+964", country: "Iraq", emoji: "🇮🇶" },
    { code: "+962", country: "Jordan", emoji: "🇯🇴" },
    { code: "+90", country: "Turkey", emoji: "🇹🇷" },
    { code: "+994", country: "Azerbaijan", emoji: "🇦🇿" },
    { code: "+995", country: "Georgia", emoji: "🇬🇪" },
    { code: "+996", country: "Kyrgyzstan", emoji: "🇰🇬" },
    { code: "+998", country: "Uzbekistan", emoji: "🇺🇿" },
    { code: "+993", country: "Turkmenistan", emoji: "🇹🇲" },
    { code: "+992", country: "Tajikistan", emoji: "🇹🇯" },
    { code: "+976", country: "Mongolia", emoji: "🇲🇳" },
    { code: "+380", country: "Ukraine", emoji: "🇺🇦" },
    { code: "+375", country: "Belarus", emoji: "🇧🇾" },
    { code: "+373", country: "Moldova", emoji: "🇲🇩" },
    { code: "+372", country: "Estonia", emoji: "🇪🇪" },
    { code: "+371", country: "Latvia", emoji: "🇱🇻" },
    { code: "+370", country: "Lithuania", emoji: "🇱🇹" },
    { code: "+386", country: "Slovenia", emoji: "🇸🇮" },
    { code: "+385", country: "Croatia", emoji: "🇭🇷" },
    { code: "+381", country: "Serbia", emoji: "🇷🇸" },
    { code: "+382", country: "Montenegro", emoji: "🇲🇪" },
    { code: "+389", country: "North Macedonia", emoji: "🇲🇰" },
    { code: "+43", country: "Austria", emoji: "🇦🇹" },
    { code: "+41", country: "Switzerland", emoji: "🇨🇭" },
    { code: "+40", country: "Romania", emoji: "🇷🇴" },
    { code: "+36", country: "Hungary", emoji: "🇭🇺" },
    { code: "+421", country: "Slovakia", emoji: "🇸🇰" },
    { code: "+420", country: "Czech Republic", emoji: "🇨🇿" },
    { code: "+48", country: "Poland", emoji: "🇵🇱" },
    { code: "+351", country: "Portugal", emoji: "🇵🇹" },
    { code: "+30", country: "Greece", emoji: "🇬🇷" },
    { code: "+34", country: "Spain", emoji: "🇪🇸" },
    { code: "+39", country: "Italy", emoji: "🇮🇹" },
    { code: "+33", country: "France", emoji: "🇫🇷" },
    { code: "+49", country: "Germany", emoji: "🇩🇪" },
    { code: "+7", country: "Russia", emoji: "🇷🇺" },
    { code: "+81", country: "Japan", emoji: "🇯🇵" },
    { code: "+61", country: "Australia", emoji: "🇦🇺" },
    { code: "+64", country: "New Zealand", emoji: "🇳🇿" },
    { code: "+1", country: "Canada", emoji: "🇨🇦" },
    { code: "+44", country: "United Kingdom", emoji: "🇬🇧" },
  ];